### PR TITLE
Make layers reusable

### LINKED ISSUE #19: Layers don't seem to be reusable
This may be by design, but the OOP api for creating layer makes it seem like they should be reusable.

--------------------------

**Repro**

I created this simple layer using the OOP api:
```lua
local layer = libmodal.layer.new({})

local count = 1
layer:map("n", "a", function()
	print("From layer - " .. tostring(count))
	count = count + 1
end, {})

layer:map("n", "<esc>", function()
	layer:exit()
end, {})

vim.keymap.set("n", "<leader>l", function()
	layer:enter()
end, {})
```

**Expected**
I can enter and exit the layer multiple times. When the layer is active the `a` keybind prints the message

**Actual**
The layer works fine the first time it is entered, but if it is exited and re-entered afterwards, none of the keybinds defined in the layer work.

-----------------------------

It feels like a layer should be able to be exited and re-entered without having to set all the keybinds on the layer object every-time it is exited.

### PR DESCRIPTION
**Pull request by itsFrank**
Fixes #19 

I extracted the functionality for removing an active mapping from `:unmap` into a new local function `unmap_existing`.

`:unmap` now calls this function where the code used to be, leaving `:unmap` unchanged.

`:exit` now calls `unmap_existing` where it used to call `:unmap`. This will remove the mapping from vim, but leave it in the layer's inactive mappings.

### CODE REVIEW

**Comment by Iron-E** [comment]
Just to let you know, I worked on this earlier. Just haven't pushed it yet because a kernel update broke wifi and I put off fixing it. 

Once I get wifi working I'll ping you, will be good to have you double check it suits your needs before a merge

**Comment by itsFrank** [comment]
Oh cool, yeah I had some free time this evening and got curious. Turns out it didn't seem too hard to fix so I gave it a shot.

I'll mark as ready for review, let me know if there's anything I missed

**Comment by Iron-E** [comment]
Sorry for the delay, something urgent came up. 

It seems merging is blocked because commits must be signed to be admitted into the master branch— do you have commit signing set up @itsFrank ?

**Comment by itsFrank** [comment]
Sorry for the force pushes, had to get signing set up. But I think it worked?

**Pull request merged**
